### ISSUE TITLE
indexes don't include duplicate rules

### ISSUE THREAD

**Issue by barctor** [KeironO/coding-errors#1]
when running the following:  
```python3
from coding errors import run

codes = [
    "N179",
    "Y529",
    "N189",	
    "E86X",
    "I952",
    "Y529",
    "I489",
    "E46",
    "R630",
    "R634",
    "R001",
    "Y520",
    "E872",
    "E876"
]

print(run(codes))
```

i get this (incorrect) message: `{'I952': {'FSCP:38:E': {'<': {'pass': False, 'relevant': ['I952'], 'note': 'One of Y40,Y41,Y42,Y43,Y44,Y45,Y46,Y47,Y48,Y49,Y50,Y51,Y52,Y53,Y54,Y55,Y56,Y57,Y58,Y59 needs to coded directly after I952'}}}}`  
might be dual rules causing the issue

**Comment by KeironO** [comment]
Hi @barctor 

I fixed this in https://github.com/KeironO/coding-errors/commit/87b14516f50bd28669e4ba2bb11f273b8a7ab71c

Thank you for your contribution
